# Generated by Django 3.2.7 on 2021-09-19 06:01

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Account',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('email', models.EmailField(max_length=60, unique=True, verbose_name='email')),
                ('username', models.CharField(max_length=60, unique=True, verbose_name='username')),
                ('date_joined', models.DateTimeField(auto_now_add=True, verbose_name='date joined')),
                ('last_login', models.DateTimeField(auto_now=True, verbose_name='last login')),
                ('is_admin', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=True)),
                ('is_staff', models.BooleanField(default=False)),
                ('is_superuser', models.BooleanField(default=False)),
                ('profile_image', models.ImageField(blank=True, default='1212', max_length=255, null=True, upload_to='')),
                ('registration_no', models.IntegerField(max_length=10, unique=True, verbose_name='registration number')),
                ('domicile_state', models.CharField(max_length=150, verbose_name='domicile state')),
                ('acad_program', models.CharField(max_length=150, verbose_name='academic program')),
                ('acad_dept', models.CharField(max_length=150, verbose_name='department')),
                ('specialisation', models.CharField(max_length=150, verbose_name='specialisation')),
                ('gender', models.CharField(max_length=15, verbose_name='gender')),
                ('cgpa', models.FloatField(verbose_name='cgpa')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
