# Generated by Django 3.2.7 on 2021-09-18 16:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_auto_20210918_1520'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='scholarship_amount',
            field=models.DecimalField(decimal_places=2, max_digits=50),
        ),
    ]
