# Generated by Django 3.2.7 on 2021-09-19 06:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0007_auto_20210919_0824'),
    ]

    operations = [
        migrations.AlterField(
            model_name='application',
            name='title',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='blog.post'),
        ),
    ]
