# Generated by Django 3.2.7 on 2021-09-19 06:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0008_alter_application_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='application',
            name='title',
            field=models.CharField(max_length=100),
        ),
    ]
